/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedFechamentoRouteImport } from './routes/_authenticated/fechamento'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFreelancersRouteImport } from './routes/_authenticated/freelancers'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as PontoTokenRouteImport } from './routes/ponto.$token'
import { Route as AuthenticatedEventosIndexRouteImport } from './routes/_authenticated/eventos.index'
import { Route as AuthenticatedEventosEventoIdRouteImport } from './routes/_authenticated/eventos.$eventoId'
import { Route as AuthenticatedOperacaoIndexRouteImport } from './routes/_authenticated/operacao.index'
import { Route as AuthenticatedOperacaoEventoIdRouteImport } from './routes/_authenticated/operacao.$eventoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFechamentoRoute = AuthenticatedFechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFreelancersRoute =
  AuthenticatedFreelancersRouteImport.update({
    id: '/freelancers',
    path: '/freelancers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PontoTokenRoute = PontoTokenRouteImport.update({
  id: '/ponto/$token',
  path: '/ponto/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventosIndexRoute =
  AuthenticatedEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosEventoIdRoute =
  AuthenticatedEventosEventoIdRouteImport.update({
    id: '/eventos/$eventoId',
    path: '/eventos/$eventoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoIndexRoute =
  AuthenticatedOperacaoIndexRouteImport.update({
    id: '/operacao/',
    path: '/operacao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoEventoIdRoute =
  AuthenticatedOperacaoEventoIdRouteImport.update({
    id: '/operacao/$eventoId',
    path: '/operacao/$eventoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/freelancers': typeof AuthenticatedFreelancersRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/ponto/$token': typeof PontoTokenRoute
  '/eventos/$eventoId': typeof AuthenticatedEventosEventoIdRoute
  '/operacao/$eventoId': typeof AuthenticatedOperacaoEventoIdRoute
  '/eventos/': typeof AuthenticatedEventosIndexRoute
  '/operacao/': typeof AuthenticatedOperacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/freelancers': typeof AuthenticatedFreelancersRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/ponto/$token': typeof PontoTokenRoute
  '/eventos/$eventoId': typeof AuthenticatedEventosEventoIdRoute
  '/operacao/$eventoId': typeof AuthenticatedOperacaoEventoIdRoute
  '/eventos': typeof AuthenticatedEventosIndexRoute
  '/operacao': typeof AuthenticatedOperacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/fechamento': typeof AuthenticatedFechamentoRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/freelancers': typeof AuthenticatedFreelancersRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/ponto/$token': typeof PontoTokenRoute
  '/_authenticated/eventos/$eventoId': typeof AuthenticatedEventosEventoIdRoute
  '/_authenticated/operacao/$eventoId': typeof AuthenticatedOperacaoEventoIdRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexRoute
  '/_authenticated/operacao/': typeof AuthenticatedOperacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/configuracoes'
    | '/fechamento'
    | '/financeiro'
    | '/freelancers'
    | '/onboarding'
    | '/painel'
    | '/relatorios'
    | '/ponto/$token'
    | '/eventos/$eventoId'
    | '/operacao/$eventoId'
    | '/eventos/'
    | '/operacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/configuracoes'
    | '/fechamento'
    | '/financeiro'
    | '/freelancers'
    | '/onboarding'
    | '/painel'
    | '/relatorios'
    | '/ponto/$token'
    | '/eventos/$eventoId'
    | '/operacao/$eventoId'
    | '/eventos'
    | '/operacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/fechamento'
    | '/_authenticated/financeiro'
    | '/_authenticated/freelancers'
    | '/_authenticated/onboarding'
    | '/_authenticated/painel'
    | '/_authenticated/relatorios'
    | '/ponto/$token'
    | '/_authenticated/eventos/$eventoId'
    | '/_authenticated/operacao/$eventoId'
    | '/_authenticated/eventos/'
    | '/_authenticated/operacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PontoTokenRoute: typeof PontoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fechamento': {
      id: '/_authenticated/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof AuthenticatedFechamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelancers': {
      id: '/_authenticated/freelancers'
      path: '/freelancers'
      fullPath: '/freelancers'
      preLoaderRoute: typeof AuthenticatedFreelancersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ponto/$token': {
      id: '/ponto/$token'
      path: '/ponto/$token'
      fullPath: '/ponto/$token'
      preLoaderRoute: typeof PontoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthenticatedEventosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/$eventoId': {
      id: '/_authenticated/eventos/$eventoId'
      path: '/eventos/$eventoId'
      fullPath: '/eventos/$eventoId'
      preLoaderRoute: typeof AuthenticatedEventosEventoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/': {
      id: '/_authenticated/operacao/'
      path: '/operacao'
      fullPath: '/operacao/'
      preLoaderRoute: typeof AuthenticatedOperacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/$eventoId': {
      id: '/_authenticated/operacao/$eventoId'
      path: '/operacao/$eventoId'
      fullPath: '/operacao/$eventoId'
      preLoaderRoute: typeof AuthenticatedOperacaoEventoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedFechamentoRoute: typeof AuthenticatedFechamentoRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFreelancersRoute: typeof AuthenticatedFreelancersRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedEventosEventoIdRoute: typeof AuthenticatedEventosEventoIdRoute
  AuthenticatedOperacaoEventoIdRoute: typeof AuthenticatedOperacaoEventoIdRoute
  AuthenticatedEventosIndexRoute: typeof AuthenticatedEventosIndexRoute
  AuthenticatedOperacaoIndexRoute: typeof AuthenticatedOperacaoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedFechamentoRoute: AuthenticatedFechamentoRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFreelancersRoute: AuthenticatedFreelancersRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedEventosEventoIdRoute: AuthenticatedEventosEventoIdRoute,
  AuthenticatedOperacaoEventoIdRoute: AuthenticatedOperacaoEventoIdRoute,
  AuthenticatedEventosIndexRoute: AuthenticatedEventosIndexRoute,
  AuthenticatedOperacaoIndexRoute: AuthenticatedOperacaoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PontoTokenRoute: PontoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
