/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConexaoRouteImport } from './routes/conexao'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as OperacaoRouteImport } from './routes/operacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConexaoRoute = ConexaoRouteImport.update({
  id: '/conexao',
  path: '/conexao',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoRoute = OperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conexao': typeof ConexaoRoute
  '/eventos': typeof EventosRoute
  '/operacao': typeof OperacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conexao': typeof ConexaoRoute
  '/eventos': typeof EventosRoute
  '/operacao': typeof OperacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conexao': typeof ConexaoRoute
  '/eventos': typeof EventosRoute
  '/operacao': typeof OperacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conexao' | '/eventos' | '/operacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conexao' | '/eventos' | '/operacao'
  id: '__root__' | '/' | '/conexao' | '/eventos' | '/operacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConexaoRoute: typeof ConexaoRoute
  EventosRoute: typeof EventosRoute
  OperacaoRoute: typeof OperacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conexao': {
      id: '/conexao'
      path: '/conexao'
      fullPath: '/conexao'
      preLoaderRoute: typeof ConexaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao': {
      id: '/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof OperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConexaoRoute: ConexaoRoute,
  EventosRoute: EventosRoute,
  OperacaoRoute: OperacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
